variables:
    AMREX_HOME: ${CI_PROJECT_DIR}/extern/amrex
    IAMR_HOME: ${CI_PROJECT_DIR}/extern/IAMR
    PELE_PHYSICS_HOME: ${CI_PROJECT_DIR}/extern/PelePhysics
    PELELM_HOME: $CI_PROJECT_DIR
    PELEREGTEST_HOME: ${CI_PROJECT_DIR}/extern/PeleRegressionTesting
    ARCHIVE_DIR: /home/m/marcd/Pele/RegressionTestBenchmarks/godzilla


stages:
    - regression

regression:godzilla:
    stage: regression
    script: 
        - git clone git@code.ornl.gov:Pele/PeleRegressionTesting ${PELEREGTEST_HOME} --branch development
        - git clone git@github.com:AMReX-Codes/amrex.git ${AMREX_HOME} --branch development
        - git clone git@github.com:AMReX-Codes/IAMR.git ${IAMR_HOME} --branch development
        - git clone git@code.ornl.gov:Pele/PelePhysics.git ${PELE_PHYSICS_HOME} --branch development
        - cd ${PELEREGTEST_HOME}/RunnerData/godzilla/PeleLM
        - \rm -rf PeleLM-benchmarks
        - ncftpget -c -E -d errlog.txt -f ${HOME}/.archive.passwd ${ARCHIVE_DIR}/PeleLM-benchmarks.cpio-latest  | cpio -i --preserve-modification-time
        - cd ${CI_PROJECT_DIR}
        - bash ${PELEREGTEST_HOME}/Scripts/prep_tests.sh ${PELEREGTEST_HOME}/Scripts/PeleLM-correct-tests-godzilla.ini  tests.ini
        - ${AMREX_HOME}/Tools/RegressionTesting/regtest.py --no_update All tests.ini
    tags:
        - godzilla
    only:
        - development

