variables:
    AMREX_HOME: ${CI_PROJECT_DIR}/extern/amrex
    IAMR_HOME: ${CI_PROJECT_DIR}/extern/IAMR
    PELE_PHYSICS_HOME: ${CI_PROJECT_DIR}/extern/PelePhysics
    PELELM_HOME: $CI_PROJECT_DIR
    PELEREGTEST_HOME: ${CI_PROJECT_DIR}/extern/PeleRegressionTesting

stages:
    - build
    - correctness

# build:rgvm:
#     stage: build
#     script: 
#         - git clone git@code.ornl.gov:Pele/PeleRegressionTesting ${PELEREGTEST_HOME} --branch development
#         - git clone git@code.ornl.gov:Pele/amrex.git ${AMREX_HOME} --branch development
#         - git clone git@code.ornl.gov:Pele/IAMR.git ${IAMR_HOME} --branch pele
#         - git clone git@code.ornl.gov:Pele/PelePhysics.git ${PELE_PHYSICS_HOME} --branch development
#         - cd ${CI_PROJECT_DIR}
#         - bash ${PELEREGTEST_HOME}/Scripts/prep_tests.sh ${PELEREGTEST_HOME}/Scripts/PeleLM-build-tests-rgvm.ini  tests.ini
#         - ${BOXLIB_HOME}/Tools/RegressionTesting/regtest.py --no_update All tests.ini
#     tags:
#         - rgvm

build:godzilla:
    stage: build
    script: 
        - git clone git@code.ornl.gov:Pele/PeleRegressionTesting ${PELEREGTEST_HOME} --branch development
        - git clone git@code.ornl.gov:Pele/amrex ${AMREX_HOME} --branch development
        - git clone git@code.ornl.gov:Pele/IAMR.git ${IAMR_HOME} --branch pele
        - git clone git@code.ornl.gov:Pele/PelePhysics.git ${PELE_PHYSICS_HOME} --branch development
        - cd ${CI_PROJECT_DIR}
        - bash ${PELEREGTEST_HOME}/Scripts/prep_tests.sh ${PELEREGTEST_HOME}/Scripts/PeleLM-build-tests-godzilla.ini  tests.ini
        - ${BOXLIB_HOME}/Tools/RegressionTesting/regtest.py --no_update All tests.ini
    tags:
        - godzilla
    only:
        - development

# correctness:rgvm:
#     stage: correctness
#     script: 
#         - git clone git@code.ornl.gov:Pele/PeleRegressionTesting ${PELEREGTEST_HOME} --branch development
#         - git clone git@code.ornl.gov:Pele/amrex ${AMREX_HOME} --branch development
#         - git clone git@code.ornl.gov:Pele/IAMR.git ${IAMR_HOME} --branch pele
#         - git clone git@code.ornl.gov:Pele/PelePhysics.git ${PELE_PHYSICS_HOME} --branch development
#         - cd ${CI_PROJECT_DIR}
#         - bash ${PELEREGTEST_HOME}/Scripts/prep_tests.sh ${PELEREGTEST_HOME}/Scripts/PeleLM-build-correct-rgvm.ini  tests.ini
#         - ${BOXLIB_HOME}/Tools/RegressionTesting/regtest.py --no_update All tests.ini
#     tags:
#         - rgvm

correctness:godzilla:
    stage: correctness
    script:
        - git clone git@code.ornl.gov:Pele/PeleRegressionTesting ${PELEREGTEST_HOME} --branch development
        - git clone git@code.ornl.gov:Pele/amrex ${AMREX_HOME} --branch development
        - git clone git@code.ornl.gov:Pele/IAMR.git ${IAMR_HOME} --branch pele
        - git clone git@code.ornl.gov:Pele/PelePhysics.git ${PELE_PHYSICS_HOME} --branch development
        - cd ${CI_PROJECT_DIR}
        - bash ${PELEREGTEST_HOME}/Scripts/prep_tests.sh ${PELEREGTEST_HOME}/Scripts/PeleLM-correct-tests-godzilla.ini  tests.ini
        - ${BOXLIB_HOME}/Tools/RegressionTesting/regtest.py --no_update All tests.ini
    tags:
        - godzilla
    only:
        - development

