name: CI_linux                                                                                                                                            

on: 
   workflow_dispatch:
      #   push:
      #     branches: [ development ]
      #   pull_request:
      #     branches: [ development ]

jobs:
   #Build the 2D FlameSheet RegTest with GNU7.5 and no MPI support
   #    FS2D_NoMPI:
   #      name: GNU@7.5 NOMPI [FS2D]
   #      runs-on: ubuntu-latest
   #      env: 
   #        {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
   #      steps:
   #      - uses: actions/checkout@v2
   #      - name: System Dependencies
   #        run: .github/workflows/dependencies/dependencies.sh
   #      - name: Repo Dependencies
   #        run: Tools/CloneDeps.sh
   #      - name: Build
   #        env:
   #           AMREX_HOME: ${GITHUB_WORKSPACE}/build/amrex
   #           IAMR_HOME: ${GITHUB_WORKSPACE}/build/IAMR
   #           PELE_PHYSICS_HOME: ${GITHUB_WORKSPACE}/build/PelePhysics
   #           PELELM_HOME: ${GITHUB_WORKSPACE}
   #        run: |
   #          cd Exec/RegTests/FlameSheet/
   #          make TPL COMP=gnu USE_MPI=FALSE
   #          make -j 2 COMP=gnu USE_MPI=FALSE
   #
   #    # Build the 2D FlameSheet RegTest with GNU7.5 and MPI support
   #    FS2D_MPI:
   #      name: GNU@7.5 MPI [FS2D]
   #      runs-on: ubuntu-latest
   #      env: 
   #        {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
   #      steps:
   #      - uses: actions/checkout@v2
   #      - name: System Dependencies
   #        run: .github/workflows/dependencies/dependencies.sh
   #      - name: Repo Dependencies
   #        run: Tools/CloneDeps.sh
   #      - name: Build
   #        env:
   #           AMREX_HOME: ${GITHUB_WORKSPACE}/build/amrex
   #           IAMR_HOME: ${GITHUB_WORKSPACE}/build/IAMR
   #           PELE_PHYSICS_HOME: ${GITHUB_WORKSPACE}/build/PelePhysics
   #           PELELM_HOME: ${GITHUB_WORKSPACE}
   #        run: |
   #          cd Exec/RegTests/FlameSheet/
   #          make TPL COMP=gnu
   #          make -j 2 COMP=gnu
   #
   #    # Build the 3D FlameSheet RegTest with GNU7.5 and MPI support
   #    FS3D_MPI:
   #      name: GNU@7.5 MPI [FS3D]
   #      runs-on: ubuntu-latest
   #      env: 
   #        {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
   #      steps:
   #      - uses: actions/checkout@v2
   #      - name: System Dependencies
   #        run: .github/workflows/dependencies/dependencies.sh
   #      - name: Repo Dependencies
   #        run: Tools/CloneDeps.sh
   #      - name: Build
   #        env:
   #           AMREX_HOME: ${GITHUB_WORKSPACE}/build/amrex
   #           IAMR_HOME: ${GITHUB_WORKSPACE}/build/IAMR
   #           PELE_PHYSICS_HOME: ${GITHUB_WORKSPACE}/build/PelePhysics
   #           PELELM_HOME: ${GITHUB_WORKSPACE}
   #        run: |
   #          cd Exec/RegTests/FlameSheet/
   #          make TPL COMP=gnu DIM=3
   #          make -j 2 COMP=gnu DIM=3

  # Build the 2D FlameSheet RegTest with CUDA and MPI support
  # TODO: Sundials compile fail with CUDA 9.1.
  FS2D_CUDA:
    name: CUDA@11.0.2 [FS2D]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System Dependencies
      run: .github/workflows/dependencies/dependencies_nvcc.sh
    - name: Repo Dependencies
      run: Tools/CloneDeps.sh
    - name: Build
      env:
         AMREX_HOME: ${GITHUB_WORKSPACE}/build/amrex
         IAMR_HOME: ${GITHUB_WORKSPACE}/build/IAMR
         PELE_PHYSICS_HOME: ${GITHUB_WORKSPACE}/build/PelePhysics
         PELELM_HOME: ${GITHUB_WORKSPACE}
      run: |
        export PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
        cd Exec/RegTests/FlameSheet/
        make help COMP=gnu USE_CUDA=TRUE
        make TPL COMP=gnu USE_CUDA=TRUE
        make -j 2 COMP=gnu USE_CUDA=TRUE
