name: CI_linux                                                                                                                                            

on: workflow_dispatch
#  push:
#    branches: [ feature_CI ]
#  pull_request:
#    branches: [ feature_CI ]

jobs:
  # Build the 2D FlameSheet RegTest with GNU and no MPI support
  FS2D:
    name: FS2D GNU NOMPI
    runs-on: ubuntu-latest
    env: {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
    steps:
    - uses: actions/checkout@v2
    - name: Clone Dependencies
      run: Tools/CloneDeps.sh
    - name: Build
      env:
         AMREX_HOME: $PWD/build/amrex
         IAMR_HOME: $PWD/build/IAMR
         PELE_PHYSICS_HOME: $PWD/build/PelePhysics
         PELELM_HOME: $PWD
      run: |
        cd Exec/RegTests/FlameSheet/
        make TPL COMP=gnu USE_MPI=FALSE
        make -j 2 COMP=gnu USE_MPI=FALSE
